from typing import List


class Constant:
    pass


class Predicate:
    pass


class VocabularyInfo:
    def __copy__(self) -> "VocabularyInfo": ...
    def __deepcopy__(self, other: "VocabularyInfo") -> "VocabularyInfo": ... 
    def add_predicate(self, name: str, arity: int, is_static: bool) -> Predicate: ...
    def add_constant(self, name: str) -> Constant: ...
    def get_predicates(self) -> List[Predicate]: ...
    def get_constants(self) -> List[Constant]: ...
    def get_predicate(self, name: str) -> Predicate: ...
    def get_constant(self, name: str) -> Constant: ...
