
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem delivery-1x2-1)
    (:domain delivery)

    (:objects
        a b - cell
        p - package
        t - truck
    )

    (:init
        (adjacent a b)
        (adjacent b a)
        (at t b)
        (at p a)
        (empty t)
    )

    (:goal
        (at p b)
    )

    
    
    
)

